AgroFichasWeb/Models/SoftwareCalidad/CAL_CertificadoBatchControlTechnicalCertificate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgroFichasWeb.Models
{
    public partial class CAL_CertificadoBatchControlTechnicalCertificate
    {
        #region 1. DataContexts
        private SoftwareCalidadDBDataContext dcSoftwareCalidad = new SoftwareCalidadDBDataContext();
        #endregion
        #region 2. Propiedades
        public int IdOrdenProduccion { get; set; }
        #endregion
        #region 3. Funciones

        #endregion
        #region 4. SelectLists
        public IEnumerable<SelectListItem> GetLotes(int? IdOrdenProduccion)
        {
            IEnumerable<SelectListItem> selectList = from X in dcSoftwareCalidad.CAL_OrdenProduccion
                                                     where X.IdTipoOrdenProduccion == 2
                                                     && X.Habilitado
                                                     && (X.Autorizado.HasValue && X.Autorizado.Value)
                                                     orderby X.LoteComercial
                                                     select new SelectListItem
                                                     {
                                                         Selected = (X.IdOrdenProduccion == IdOrdenProduccion && IdOrdenProduccion != null),
                                                         Text = X.LoteComercial,
                                                         Value = X.IdOrdenProduccion.ToString()
                                                     };
            return selectList;
        }

        public IEnumerable<SelectListItem> GetLotesPallets(int? IdOrdenProduccion)
        {
            IEnumerable<SelectListItem> selectList = from X in dcSoftwareCalidad.CAL_OrdenProduccion
                                                     where X.IdTipoOrdenProduccion == 1
                                                     && X.Habilitado
                                                     && (X.Autorizado.HasValue && X.Autorizado.Value)
                                                     orderby X.LoteComercial
                                                     select new SelectListItem
                                                     {
                                                         Selected = (X.IdOrdenProduccion == IdOrdenProduccion && IdOrdenProduccion != null),
                                                         Text = X.LoteComercial,
                                                         Value = X.IdOrdenProduccion.ToString()
                                                     };
            return selectList;
        }
        #endregion
        #region 5. Validaciones
        public bool IsValid
        {
            get { return (GetRuleViolations().Count() == 0); }
        }

        public IEnumerable<RuleViolation> GetRuleViolations()
        {
            if (string.IsNullOrEmpty(this.CertificateNumber))
                yield return new RuleViolation("El número de certificado es requerido", "CertificateNumber");

            //if (string.IsNullOrEmpty(this.ProductionDate))
            //    yield return new RuleViolation("La fecha de producción es requerida", "ProductionDate");

            if (string.IsNullOrEmpty(this.ProcessCode))
                yield return new RuleViolation("El código del proceso es requerido", "ProcessCode");

            if (string.IsNullOrEmpty(this.Presentation))
                yield return new RuleViolation("La presentación es requerida", "Presentation");

            yield break;
        }

        partial void OnValidate(System.Data.Linq.ChangeAction action)
        {
            if (!IsValid)
                throw new ApplicationException("Rule violations prevent saving");
        }
        #endregion
    }
}

AgroFichasWeb/Controllers/SoftwareCalidad/CALCertificadoBatchControlTechnicalCertificateController.cs
using AgroFichasWeb.Controllers.Filters;
using AgroFichasWeb.Models;
using MoreLinq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AgroFichasWeb.Controllers.SoftwareCalidad
{
    [WebsiteAuthorize]
    public class CALCertificadoBatchControlTechnicalCertificateController : BaseApplicationController
    {
        private SoftwareCalidadDBDataContext dcSoftwareCalidad = new SoftwareCalidadDBDataContext();
        private AgroFichasDBDataContext dcAgroFichas = new AgroFichasDBDataContext();

        public CALCertificadoBatchControlTechnicalCertificateController()
        {
            SetCurrentModulo(10);
        }

        // GET: CALCertificadoBatchControlTechnicalCertificate
        public ActionResult Index(int? id, int? IdPlantaProduccion)
        {
            CheckPermisoAndRedirect(377);

            var IdPlantaProduccionSelect = IdPlantaProduccion ?? 0;

            IEnumerable<SelectListItem> plantas = from us in dcAgroFichas.PlantaUsuario
                                                  join pl in dcAgroFichas.PlantaProduccion on us.IdPlantaProduccion equals pl.IdPlantaProduccion
                                                  where us.UserID == CurrentUser.UserID
                                                  && pl.Habilitado
                                                  select new SelectListItem
                                                  {
                                                      Value = pl.IdPlantaProduccion.ToString(),
                                                      Text = pl.Nombre,
                                                      Selected = IdPlantaProduccionSelect == pl.IdPlantaProduccion
                                                  };
            PlantaUsuario pu = CurrentUser.PlantaUsuario.FirstOrDefault();

            if (!object.ReferenceEquals(pu, null) && object.ReferenceEquals(IdPlantaProduccion, null))
            {
                IdPlantaProduccionSelect = pu.IdPlantaProduccion;
            }

            List<CAL_CertificadoBatchControlTechnicalCertificate> list = dcSoftwareCalidad.CAL_CertificadoBatchControlTechnicalCertificate
                .Where(X => X.Habilitado == true && X.CAL_LEPallets.CAL_OrdenProduccion.IdPlanta == IdPlantaProduccionSelect)
                .OrderByDescending(X => X.FechaHoraIns)
                .OrderByDescending(X => X.IdCertificadoBatchControlTechnicalCertificate).ToList();
            ViewData["errMsg"] = Request["errMsg"];
            ViewData["okMsg"] = Request["okMsg"];
            ViewData["PlantasProduccion"] = plantas;
            ViewData["permisosUsuario"] = new Permiso(CheckPermiso(378),
                                                      CheckPermiso(377),
                                                      CheckPermiso(379),
                                                      CheckPermiso(380));
            return View(list);
        }

        public ActionResult Crear()
        {
            CheckPermisoAndRedirect(378);
            CAL_CertificadoBatchControlTechnicalCertificate cert = new CAL_CertificadoBatchControlTechnicalCertificate();
            return View(cert);
        }

        [HttpPost]
        public ActionResult Crear(CAL_CertificadoBatchControlTechnicalCertificate cert, FormCollection formCollection)
        {
            CheckPermisoAndRedirect(378);
            if (ModelState.IsValid)
            {
                try
                {
                    var fts = dcSoftwareCalidad.CAL_GetFichasTecnicasPorListaEmpaque_Pallets(cert.IdLEPallets).ToList();
                    var CustomerCode = "";
                    var VersionSpecification = "";
                    foreach (var ft in fts)
                    {
                        CustomerCode += ft.Codigo + "/";
                        VersionSpecification += ft.Version + "/";
                    }
                    cert.CustomerCode = CustomerCode.Remove(CustomerCode.Length - 1);
                    cert.VersionSpecification = VersionSpecification.Remove(VersionSpecification.Length - 1);

                    // Actualizar Luego
                    cert.ProductionDate = "";
                    cert.CustomerName = "";
                    cert.Container = 0;
                    cert.AmountProduct = 0;
                    cert.CertifiedTon = 0;
                    cert.BookingNumber = "";
                    cert.ShippingLineAndVessel = "";
                    cert.Lot = "";
                    cert.CertificateKey = "";

                    // Rescatados del Form
                    cert.ProductionDate = cert.ProductionDate.ToUpper();
                    cert.ProcessCode = cert.ProcessCode.ToUpper();
                    cert.Habilitado = true;
                    cert.FechaHoraIns = DateTime.Now;
                    cert.IpIns = RemoteAddr();
                    cert.UserIns = User.Identity.Name;
                    dcSoftwareCalidad.CAL_CertificadoBatchControlTechnicalCertificate.InsertOnSubmit(cert);
                    dcSoftwareCalidad.SubmitChanges();

                    // Actualizado
                    cert.CustomerName = cert.CAL_LEPallets.CAL_OrdenProduccion.GetCliente(cert.CAL_LEPallets.CAL_OrdenProduccion.IdCliente).RazonSocial.ToUpper();
                    cert.Lot = cert.CAL_LEPallets.CAL_OrdenProduccion.LoteComercial;
                    cert.Container = (from X in dcSoftwareCalidad.CAL_LEPallets
                                      join Y in dcSoftwareCalidad.CAL_LEPalletsContenedor on X.IdLEPallets equals Y.IdLEPallets
                                      where X.IdLEPallets == cert.IdLEPallets
                                      select Y).Count();
                    cert.AmountProduct = (from X in dcSoftwareCalidad.CAL_LEPallets
                                          join Y in dcSoftwareCalidad.CAL_LEPalletsContenedor on X.IdLEPallets equals Y.IdLEPallets
                                          where X.IdLEPallets == cert.IdLEPallets
                                          select Y).Sum(X => X.PesoBruto);
                    cert.CertifiedTon = Convert.ToDecimal(((from X in dcSoftwareCalidad.CAL_LEPallets
                                                            join Y in dcSoftwareCalidad.CAL_LEPalletsContenedor on X.IdLEPallets equals Y.IdLEPallets
                                                            where X.IdLEPallets == cert.IdLEPallets
                                                            select Y).Sum(X => X.PesoBruto) / 1000M));
                    cert.BookingNumber = cert.CAL_LEPallets.NReserva;
                    cert.ShippingLineAndVessel = string.Format("{0}, {1}", cert.CAL_LEPallets.Carrier.Nombre, cert.CAL_LEPallets.Barco.Nombre);
                    cert.Lot = cert.CAL_LEPallets.CAL_OrdenProduccion.LoteComercial;

                    foreach (var fecha in dcSoftwareCalidad.CAL_GetFechasElaboracionPorOrdenProduccion_Pallets(cert.CAL_LEPallets.CAL_OrdenProduccion.IdOrdenProduccion))
                    {
                        cert.ProductionDate += string.Format("{0:dd/MM/yyyy},", fecha.FechaElaboracion);
                    }

                    cert.ProductionDate = cert.ProductionDate.Remove(cert.ProductionDate.Length - 1);
                    dcSoftwareCalidad.SubmitChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    var rv = cert.GetRuleViolations();
                    if (rv.Count() > 0)
                        ModelState.AddRuleViolations(rv);
                    else
                        throw;
                }
            }

            return View(cert);
        }

        public ActionResult CrearPDF_en(int id)
        {
            CheckPermisoAndRedirect(377);
            CAL_CertificadoBatchControlTechnicalCertificate cert = dcSoftwareCalidad.CAL_CertificadoBatchControlTechnicalCertificate.SingleOrDefault(X => X.IdCertificadoBatchControlTechnicalCertificate == id && X.Habilitado == true);
            if (cert == null)
            {
                return RedirectToAction("Index", new { errMsg = "No se ha encontrado el certificado", okMsg = "" });
            }

            var idDetalleOP = dcSoftwareCalidad.CAL_GetIDSControlGroatsPorDetalleYContenedor_ListaEmpaquePallets(cert.IdLEPallets).First();
            var produccionPorLote = dcSoftwareCalidad.CAL_GetProduccionPorLote(idDetalleOP.IdOrdenProduccion).ToList();
            var cabecera = produccionPorLote.First(X => X.IdDetalleOrdenProduccion == idDetalleOP.IdDetalleOrdenProduccion);

            string htmlContent = System.IO.File.ReadAllText(Server.MapPath("~/App_Data/certificados/batch-control-of-technical-certificate.html"), Encoding.UTF8);
            RepTemp(ref htmlContent, "FECHA", DateTime.Now.ToString("dddd, dd MMMM yyyy"));
            RepTemp(ref htmlContent, "NO", cert.CertificateNumber.ToString());
            RepTemp(ref htmlContent, "AÑO", DateTime.Now.Year.ToString());
            RepTemp(ref htmlContent, "CUSTOMERCODE", cert.CustomerCode);
            RepTemp(ref htmlContent, "VERSIONSPECIFICATION", cert.VersionSpecification);
            RepTemp(ref htmlContent, "CUSTOMERNAME", cert.CustomerName);
            RepTemp(ref htmlContent, "CONTAINER", cert.Container.ToString());
            RepTemp(ref htmlContent, "AMOUNTOFPRODUCT", cert.AmountProduct.ToString("N0"));
            RepTemp(ref htmlContent, "CERTIFIEDTON", cert.CertifiedTon.ToString("N2"));
            RepTemp(ref htmlContent, "BOOKING", cert.BookingNumber);
            RepTemp(ref htmlContent, "SHIPPINGLINE", cert.ShippingLineAndVessel);
            RepTemp(ref htmlContent, "LOT", cert.Lot);
            RepTemp(ref htmlContent, "PRODUCTIONDATE", cert.ProductionDate);
            RepTemp(ref htmlContent, "PROCESSCODE", cert.ProcessCode);

AgroFichasWeb/Views/CALCertificadoBatchControlTechnicalCertificate/ControlVersiones.cshtml
@using AgroFichasWeb.Models
@model List<CAL_CertificadoControlVersion>
@{
    ViewBag.Title = "Control de Versiones - Batch Control Of Technical Certificate";
    Layout = "~/Views/Shared/_ResponsiveLayoutVertical.cshtml";
    Permiso permisosUsuario = (Permiso)ViewData["permisosUsuario"];
    var cert = (CAL_CertificadoBatchControlTechnicalCertificate)ViewData["cert"];
}
@section VendorCSS
{
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2-bootstrap-theme/select2-bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/css/datatables.css")" />
}
@section VendorScripts
{
    <script src="@Url.Content("~/Content/porto/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/media/js/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/js/datatables.js")"></script>
}
@section CustomScripts
{
    <script>
        $('#datatable').dataTable({
            "ordering": true,
            "order": [0, 'desc'],
            "searching": true,
            "lengthChange": true,
            "language": {
                "emptyTable": "No hay registros"
            }
        });
    </script>
}

@if (!string.IsNullOrEmpty(Request["errMsg"]) || !string.IsNullOrEmpty(Request["okMsg"]))
{
    <div class="row">
        @if (!string.IsNullOrEmpty(Request["errMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["errMsg"]
                    </div>
                </div>
            </div>
        }
        @if (!string.IsNullOrEmpty(Request["okMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["okMsg"]
                    </div>
                </div>
            </div>
        }
    </div>
}
<section class="panel">
    <header class="panel-heading">
        <h2 class="panel-title">Control de Versiones</h2>
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Certificado</th>
                    <th>Firma</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr valign="top">
                        <td>@item.IdCertificadoControlVersion</td>
                        <td>@item.CAL_TipoCertificado.Nombre</td>
                        <td>@item.certkey</td>
                        <td>@item.FechaHoraIns<br />@item.UserIns</td>
                        <td>
                            <button id="pdfcreator_@item.IdCertificadoControlVersion" onclick="window.location.href='@Url.Action("DescargarPDF_ControlVersion", new { id = cert.IdCertificadoBatchControlTechnicalCertificate, item.certkey })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Descargar PDF"> <i class="fa fa-file-pdf-o"></i></button>
                            @if (permisosUsuario.Borrar)
                            {
                                <button id="delete_@item.IdCertificadoControlVersion" onclick="window.location.href='@Url.Action("Eliminar_ControlVersion", new { id = item.IdCertificadoControlVersion })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Eliminar"> <i class="fa fa-trash-o"></i></button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->

AgroFichasWeb/Views/CALCertificadoBatchControlTechnicalCertificate/Index.cshtml
@using AgroFichasWeb.Models
@model List<CAL_CertificadoBatchControlTechnicalCertificate>
@{
    ViewBag.Title = "Batch Control Of Technical Certificate";
    Layout = "~/Views/Shared/_ResponsiveLayoutVertical.cshtml";
    Permiso permisosUsuario = (Permiso)ViewData["permisosUsuario"];
    var plantas = (IEnumerable<SelectListItem>)ViewData["PlantasProduccion"];
}
@section VendorCSS
{
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2-bootstrap-theme/select2-bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/css/datatables.css")" />
}
@section VendorScripts
{
    <script src="@Url.Content("~/Content/porto/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/media/js/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/js/datatables.js")"></script>
}
@section CustomScripts
{
    <script>
        $('#datatable').dataTable({
            "ordering": true,
            "order": [0, 'desc'],
            "searching": true,
            "lengthChange": true,
            "language": {
                "emptyTable": "No hay registros"
            }
        });
    </script>
}

@if (!string.IsNullOrEmpty(Request["errMsg"]) || !string.IsNullOrEmpty(Request["okMsg"]))
{
    <div class="row">
        @if (!string.IsNullOrEmpty(Request["errMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["errMsg"]
                    </div>
                </div>
            </div>
        }
        @if (!string.IsNullOrEmpty(Request["okMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["okMsg"]
                    </div>
                </div>
            </div>
        }
    </div>
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Filtros de Búsqueda</h2>
            </header>
            <div class="panel-body">
                <div class="form-inline center">
                    @using (Html.BeginForm("index", "CALCertificadoBatchControlTechnicalCertificate", new { id = 0 }, FormMethod.Get))
                    {
                        <div class="form-group">
                            @Html.DropDownList("IdPlantaProduccion", plantas, new { @class = "form-control" })
                        </div>

                        <div class="visible-sm clearfix mt-sm mb-sm"></div>
                        <input class="btn btn-default" type="submit" value="Buscar" />
                        <div class="clearfix visible-xs mb-sm"></div>
                    }
                </div>
            </div>
        </section>
    </div>
</div>
<section class="panel">
    <header class="panel-heading">
        <h2 class="panel-title">Administrar Certificados</h2>
        <div class="mb-md" style="right: 15px;position: absolute;top: 15px;">
            <a href="@Url.Action("Crear", "CALCertificadoBatchControlTechnicalCertificate", new { })" class="btn btn-primary">Crear Certificado <i class="fa fa-plus"></i></a>
        </div>
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Certificado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr valign="top">
                        <td>@item.IdCertificadoBatchControlTechnicalCertificate</td>
                        <td>@string.Format("Batch Control {0}/{1}", item.CertificateNumber, item.FechaHoraIns.Year)</td>
                        <td>
                            <button id="pdfcreator_@item.IdCertificadoBatchControlTechnicalCertificate" onclick="window.location.href='@Url.Action("CrearPDF_es", new { id = item.IdCertificadoBatchControlTechnicalCertificate })'" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="PDF / ESPAÑOL"> <i class="fa fa-file-pdf-o"></i></button>
                            <button id="pdfcreator_@item.IdCertificadoBatchControlTechnicalCertificate" onclick="window.location.href='@Url.Action("CrearPDF_en", new { id = item.IdCertificadoBatchControlTechnicalCertificate })'" class="btn btn-tertiary" style="background-color:#0088cc;color: white" data-toggle="tooltip" data-placement="top" title="PDF / INGLÉS"> <i class="fa fa-file-pdf-o"></i></button>
                            <button id="controlversiones_@item.IdCertificadoBatchControlTechnicalCertificate" onclick="window.location.href='@Url.Action("ControlVersiones", new { id = item.IdCertificadoBatchControlTechnicalCertificate })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Control de Versiones"> <i class="fa fa-exchange"></i></button>
                            @if (permisosUsuario.Borrar)
                            {
                        <button id="delete_@item.IdCertificadoBatchControlTechnicalCertificate" onclick="window.location.href='@Url.Action("Eliminar", new { id = item.IdCertificadoBatchControlTechnicalCertificate })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Eliminar"> <i class="fa fa-trash-o"></i></button>}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->