AgroFichasWeb/Controllers/SoftwareCalidad/CALParametrosMicrobiologiaController.cs
using AgroFichasWeb.Controllers.Filters;
using AgroFichasWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgroFichasWeb.Controllers.SoftwareCalidad
{
    [WebsiteAuthorize]
    public class CALParametrosMicrobiologiaController : BaseApplicationController 
    {
        // GET: CALParametrosMicrobiologia

        private SoftwareCalidadDBDataContext dc = new SoftwareCalidadDBDataContext();

        public CALParametrosMicrobiologiaController()
        {
            SetCurrentModulo(10);
        }

        public ActionResult Index(int? id)
        {
            CheckPermisoAndRedirect(348);
            List<CAL_ParametroMicrobiologia> list = dc.CAL_ParametroMicrobiologia.Where(X => X.Habilitado == true).ToList();
            ViewData["errMsg"] = Request["errMsg"];
            ViewData["okMsg"] = Request["okMsg"];
            ViewData["permisosUsuario"] = new Permiso(CheckPermiso(349),
                                                      CheckPermiso(348),
                                                      CheckPermiso(350),
                                                      CheckPermiso(351));
            return View(list);
        }

        public ActionResult Crear()
        {
            CheckPermisoAndRedirect(349);
            CAL_ParametroMicrobiologia parametroMicrobiologia = new CAL_ParametroMicrobiologia();
            return View("Crear", parametroMicrobiologia);
        }

        [HttpPost]
        public ActionResult Crear(CAL_ParametroMicrobiologia parametroMicrobiologia)
        {
            CheckPermisoAndRedirect(349);
            if (ModelState.IsValid)
            {
                try
                {
                    if (string.IsNullOrEmpty(parametroMicrobiologia.FormatString))
                        parametroMicrobiologia.FormatString = string.Empty;

                    //Parámetros (en)
                    if (string.IsNullOrEmpty(parametroMicrobiologia.Nombre_en))
                        parametroMicrobiologia.Nombre_en = string.Empty;
                    if (string.IsNullOrEmpty(parametroMicrobiologia.FormatString_en))
                        parametroMicrobiologia.FormatString_en = string.Empty;
                    if (string.IsNullOrEmpty(parametroMicrobiologia.UM_en))
                        parametroMicrobiologia.UM_en = string.Empty;

                    parametroMicrobiologia.Habilitado = true;
                    parametroMicrobiologia.FechaHoraIns = DateTime.Now;
                    parametroMicrobiologia.IpIns = RemoteAddr();
                    parametroMicrobiologia.UserIns = User.Identity.Name;
                    dc.CAL_ParametroMicrobiologia.InsertOnSubmit(parametroMicrobiologia);
                    dc.SubmitChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    var rv = parametroMicrobiologia.GetRuleViolations();
                    if (rv.Count() > 0)
                        ModelState.AddRuleViolations(rv);
                    else
                        throw;
                }
            }

            return View("Crear", parametroMicrobiologia);
        }

        public ActionResult Editar(int id)
        {
            CheckPermisoAndRedirect(350);
            CAL_ParametroMicrobiologia parametroMicrobiologia = dc.CAL_ParametroMicrobiologia.SingleOrDefault(X => X.IdParametroMicrobiologia == id && X.Habilitado == true);
            if (parametroMicrobiologia == null) { return RedirectToAction("Index", new { errMsg = "No se ha encontrado el parámetro de microbiología", okMsg = "" }); }

            return View("Crear", parametroMicrobiologia);
        }

        [HttpPost]
        public ActionResult Editar(int id, FormCollection formValues)
        {
            CheckPermisoAndRedirect(350);
            CAL_ParametroMicrobiologia parametroMicrobiologia = dc.CAL_ParametroMicrobiologia.SingleOrDefault(X => X.IdParametroMicrobiologia == id && X.Habilitado == true);
            if (parametroMicrobiologia == null) { return RedirectToAction("Index", new { errMsg = "No se ha encontrado el parámetro de microbiología", okMsg = "" }); }

            try
            {
                UpdateModel(parametroMicrobiologia, new string[] { "Nombre", "NombreCorto", "FormatString", "UM", "Decimales", "Nombre_en", "NombreCorto_en", "FormatString_en", "UM_en" });

                if (string.IsNullOrEmpty(parametroMicrobiologia.FormatString))
                    parametroMicrobiologia.FormatString = string.Empty;

                //Parámetros (en)
                if (string.IsNullOrEmpty(parametroMicrobiologia.Nombre_en))
                    parametroMicrobiologia.Nombre_en = string.Empty;
                if (string.IsNullOrEmpty(parametroMicrobiologia.FormatString_en))
                    parametroMicrobiologia.FormatString_en = string.Empty;
                if (string.IsNullOrEmpty(parametroMicrobiologia.UM_en))
                    parametroMicrobiologia.UM_en = string.Empty;

                parametroMicrobiologia.UserUpd = User.Identity.Name;
                parametroMicrobiologia.FechaHoraUpd = DateTime.Now;
                parametroMicrobiologia.IpUpd = RemoteAddr();
                dc.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                var rv = parametroMicrobiologia.GetRuleViolations();
                if (rv.Count() > 0)
                    ModelState.AddRuleViolations(rv);
                else
                    throw;
            }

            return View("Crear", parametroMicrobiologia);
        }

        public ActionResult Eliminar(int id)
        {
            CheckPermisoAndRedirect(351);
            CAL_ParametroMicrobiologia parametroMicrobiologia = dc.CAL_ParametroMicrobiologia.SingleOrDefault(X => X.IdParametroMicrobiologia == id && X.Habilitado == true);
            if (parametroMicrobiologia == null) { return RedirectToAction("Index", new { errMsg = "No se ha encontrado el parámetro de microbiología", okMsg = "" }); }

            string errMsg = "";
            string okMsg = "";

            try
            {
                parametroMicrobiologia.Habilitado = false;
                parametroMicrobiologia.UserUpd = User.Identity.Name;
                parametroMicrobiologia.FechaHoraUpd = DateTime.Now;
                parametroMicrobiologia.IpUpd = RemoteAddr();
                dc.SubmitChanges();
                okMsg = String.Format("El parámetro de microbiología {0} ha sido eliminado", parametroMicrobiologia.Nombre);
            }
            catch (Exception ex)
            {
                errMsg = ex.Message;
            }

            return RedirectToAction("Index", new { errMsg = errMsg, okMsg = okMsg });
        }
    }
}

AgroFichasWeb/Views/CALParametrosMicrobiologia/Crear.cshtml
@using AgroFichasWeb.Models
@model CAL_ParametroMicrobiologia
@{
    ViewBag.Title = "Parámetros de Microbiología";
    Layout = "~/Views/Shared/_ResponsiveLayoutVertical.cshtml";

    if (Model.IdParametroMicrobiologia == 0)
    {
        ViewBag.SubTitle = "Crear Parámetro de Microbiología";
    }
    else
    {
        ViewBag.SubTitle = "Editar Parámetro de Microbiología";
    }
}
@section CustomScripts
{
    <script>
        $(document).ready(function () {
            if ($(".field-validation-error").html() != "") {
                $(".field-validation-error").show();
            }
        });
    </script>
}

<!-- start: page -->
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">@ViewBag.SubTitle</h2>
            </header>
            @using (Html.BeginForm())
            {
                <div class="panel-body">
                    <div class="form-horizontal form-bordered">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">Nombre <span class="required">*</span></label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("Nombre", Model.Nombre, new { @class = "form-control", maxlength = "50" })
                                        @Html.ValidationMessage("Nombre")
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">FormatString</label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("FormatString", Model.FormatString, new { @class = "form-control", maxlength = "20" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">UM <span class="required">*</span></label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("UM", Model.UM, new { @class = "form-control", maxlength = "20" })
                                        @Html.ValidationMessage("UM")
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">Decimales</label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("Decimales", Model.Decimales, new { @class = "form-control", maxlength = "50" })
                                        @Html.ValidationMessage("Decimales")
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">Nombre (en)</label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("Nombre_en", Model.Nombre_en, new { @class = "form-control", maxlength = "50" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">FormatString (en)</label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("FormatString_en", Model.FormatString_en, new { @class = "form-control", maxlength = "50" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label">UM (en)</label>
                                    <div class="col-sm-6">
                                        @Html.TextBox("UM_en", Model.UM_en, new { @class = "form-control", maxlength = "50" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <footer class="panel-footer">
                    <div class="row">
                        <div class="col-lg-12 center">
                            <input type="submit" class="btn btn-primary" value="Guardar este Parámetro de Microbiología" />
                        </div>
                    </div>
                </footer>
            }
        </section>
    </div>
</div>
<!-- end: page -->

AgroFichasWeb/Views/CALParametrosMicrobiologia/Index.cshtml
@using AgroFichasWeb.Models
@model List<CAL_ParametroMicrobiologia>
@{
    ViewBag.Title = "Parámetros de Microbiología";
    Layout = "~/Views/Shared/_ResponsiveLayoutVertical.cshtml";
    Permiso permisosUsuario = (Permiso)ViewData["permisosUsuario"];
}
@section VendorCSS
{
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/select2-bootstrap-theme/select2-bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/css/datatables.css")" />
}
@section VendorScripts
{
    <script src="@Url.Content("~/Content/porto/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/media/js/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js")"></script>
    <script src="@Url.Content("~/Content/porto/vendor/jquery-datatables-bs3/assets/js/datatables.js")"></script>
}
@section CustomScripts
{
    <script>
        $('#datatable').dataTable({
            "ordering": true,
            "order": [0, 'asc'],
            "searching": true,
            "lengthChange": true,
            "language": {
                "emptyTable": "No hay registros"
            },
            "pageLength": 100
        });
    </script>
}

@if (!string.IsNullOrEmpty(Request["errMsg"]) || !string.IsNullOrEmpty(Request["okMsg"]))
{
    <div class="row">
        @if (!string.IsNullOrEmpty(Request["errMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["errMsg"]
                    </div>
                </div>
            </div>
        }
        @if (!string.IsNullOrEmpty(Request["okMsg"]))
        {
            <div class="col-sm-12">
                <div class="mb-md">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        @Request["okMsg"]
                    </div>
                </div>
            </div>
        }
    </div>
}
<section class="panel">
    <header class="panel-heading">
        <h2 class="panel-title">Administrar Parámetros de Microbiología</h2>
        @if (permisosUsuario.Crear)
        {
            <div class="mb-md" style="right: 15px;position: absolute;top: 15px;">
                <a href="@Url.Action("Crear", "CALParametrosMicrobiologia", new { })" class="btn btn-primary">Crear Parámetro de Microbiología <i class="fa fa-plus"></i></a>
            </div>
        }
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>FormatString</th>
                    <th>UM</th>
                    <th>Nombre (en)</th>
                    <th>FormatString (en)</th>
                    <th>UM (en)</th>
                    <th>Decimales</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr valign="top">
                        <td>@item.IdParametroMicrobiologia</td>
                        <td><em>@item.Nombre</em></td>
                        <td>@item.FormatString</td>
                        <td>@item.UM</td>
                        <td><em>@item.Nombre_en</em></td>
                        <td>@item.FormatString_en</td>
                        <td>@item.UM_en</td>
                        <td>@item.Decimales</td>
                        <td>
                            @if (permisosUsuario.Actualizar)
                            {
                                <button id="edit_@item.IdParametroMicrobiologia" onclick="window.location.href='@Url.Action("Editar", new { id = item.IdParametroMicrobiologia })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Editar"> <i class="fa fa-edit"></i></button>
                            }
                            @if (permisosUsuario.Borrar)
                            {
                                <button id="delete_@item.IdParametroMicrobiologia" onclick="window.location.href='@Url.Action("Eliminar", new { id = item.IdParametroMicrobiologia })'" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Eliminar"> <i class="fa fa-trash-o"></i></button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->